[2023-11-29T14:03:49.373+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.webscrape scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-11-29T14:03:49.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: football-etl.webscrape scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-11-29T14:03:49.391+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:03:49.391+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-11-29T14:03:49.392+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-29T14:03:49.657+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): webscrape> on 2023-02-06 00:00:00+00:00
[2023-11-29T14:03:49.667+0000] {standard_task_runner.py:55} INFO - Started process 3059 to run task
[2023-11-29T14:03:49.669+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'football-etl', 'webscrape', 'scheduled__2023-02-06T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dag-football.py', '--cfg-path', '/tmp/tmp0y_pkoxu']
[2023-11-29T14:03:49.671+0000] {standard_task_runner.py:83} INFO - Job 228: Subtask webscrape
[2023-11-29T14:03:49.759+0000] {task_command.py:388} INFO - Running <TaskInstance: football-etl.webscrape scheduled__2023-02-06T00:00:00+00:00 [running]> on host 6377c365460c
[2023-11-29T14:03:49.875+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=football-etl
AIRFLOW_CTX_TASK_ID=webscrape
AIRFLOW_CTX_EXECUTION_DATE=2023-02-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-06T00:00:00+00:00
[2023-11-29T14:03:50.544+0000] {selenium_manager.py:133} WARNING - The version of firefox cannot be detected. Trying with latest driver version
[2023-11-29T14:03:50.546+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/selenium_manager.py", line 97, in driver_location
    options.binary_location = browser_path
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/options.py", line 72, in binary_location
    self.binary = value
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/options.py", line 57, in binary
    new_binary = FirefoxBinary(new_binary)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 48, in __init__
    self._start_cmd = self._get_firefox_start_cmd()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 180, in _get_firefox_start_cmd
    "Could not find firefox in your system PATH."
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script/webscrape.py", line 14, in scrape_premier_league_data
    driver = webdriver.Firefox(options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2023-11-29T14:03:50.561+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=football-etl, task_id=webscrape, execution_date=20230206T000000, start_date=20231129T140349, end_date=20231129T140350
[2023-11-29T14:03:50.590+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 228 for task webscrape (Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
; 3059)
[2023-11-29T14:03:50.605+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-29T14:03:50.640+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
